/* 2026 FIFA World Cup — group stage fixtures (ET). Source: FIFA draw / fwclive.com */
window.WC2026 = window.WC2026 || {};

window.WC2026.GROUPS = {
  A: ["Mexico", "South Africa", "Korea Republic", "Czechia"],
  B: ["Canada", "Qatar", "Switzerland", "Bosnia and Herzegovina"],
  C: ["Brazil", "Morocco", "Haiti", "Scotland"],
  D: ["USA", "Paraguay", "Australia", "Türkiye"],
  E: ["Germany", "Côte d'Ivoire", "Curaçao", "Ecuador"],
  F: ["Netherlands", "Japan", "Sweden", "Tunisia"],
  G: ["Belgium", "Egypt", "IR Iran", "New Zealand"],
  H: ["Spain", "Cabo Verde", "Saudi Arabia", "Uruguay"],
  I: ["France", "Senegal", "Iraq", "Norway"],
  J: ["Argentina", "Algeria", "Austria", "Jordan"],
  K: ["Portugal", "Congo DR", "Uzbekistan", "Colombia"],
  L: ["England", "Croatia", "Ghana", "Panama"]
};

window.WC2026.FLAGS = {
  "Mexico": "🇲🇽",
  "South Africa": "🇿🇦",
  "Korea Republic": "🇰🇷",
  "Czechia": "🇨🇿",
  "Canada": "🇨🇦",
  "Qatar": "🇶🇦",
  "Switzerland": "🇨🇭",
  "Bosnia and Herzegovina": "🇧🇦",
  "Brazil": "🇧🇷",
  "Morocco": "🇲🇦",
  "Haiti": "🇭🇹",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "USA": "🇺🇸",
  "Paraguay": "🇵🇾",
  "Australia": "🇦🇺",
  "Türkiye": "🇹🇷",
  "Germany": "🇩🇪",
  "Côte d'Ivoire": "🇨🇮",
  "Curaçao": "🇨🇼",
  "Ecuador": "🇪🇨",
  "Netherlands": "🇳🇱",
  "Japan": "🇯🇵",
  "Sweden": "🇸🇪",
  "Tunisia": "🇹🇳",
  "Belgium": "🇧🇪",
  "Egypt": "🇪🇬",
  "IR Iran": "🇮🇷",
  "New Zealand": "🇳🇿",
  "Spain": "🇪🇸",
  "Cabo Verde": "🇨🇻",
  "Saudi Arabia": "🇸🇦",
  "Uruguay": "🇺🇾",
  "France": "🇫🇷",
  "Senegal": "🇸🇳",
  "Iraq": "🇮🇶",
  "Norway": "🇳🇴",
  "Argentina": "🇦🇷",
  "Algeria": "🇩🇿",
  "Austria": "🇦🇹",
  "Jordan": "🇯🇴",
  "Portugal": "🇵🇹",
  "Congo DR": "🇨🇩",
  "Uzbekistan": "🇺🇿",
  "Colombia": "🇨🇴",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Croatia": "🇭🇷",
  "Ghana": "🇬🇭",
  "Panama": "🇵🇦"
};

window.WC2026.MATCHES = [
  { id: 1, date: "2026-06-11", time: "15:00", home: "Mexico", away: "South Africa", group: "A", venue: "Mexico City Stadium", matchday: 1 },
  { id: 2, date: "2026-06-11", time: "22:00", home: "Korea Republic", away: "Czechia", group: "A", venue: "Estadio Guadalajara", matchday: 1 },
  { id: 3, date: "2026-06-12", time: "15:00", home: "Canada", away: "Bosnia and Herzegovina", group: "B", venue: "Toronto Stadium", matchday: 1 },
  { id: 4, date: "2026-06-12", time: "21:00", home: "USA", away: "Paraguay", group: "D", venue: "Los Angeles Stadium", matchday: 1 },
  { id: 5, date: "2026-06-13", time: "21:00", home: "Haiti", away: "Scotland", group: "C", venue: "Boston Stadium", matchday: 1 },
  { id: 6, date: "2026-06-14", time: "00:00", home: "Australia", away: "Türkiye", group: "D", venue: "BC Place Vancouver", matchday: 1 },
  { id: 7, date: "2026-06-13", time: "18:00", home: "Brazil", away: "Morocco", group: "C", venue: "New York New Jersey Stadium", matchday: 1 },
  { id: 8, date: "2026-06-13", time: "15:00", home: "Qatar", away: "Switzerland", group: "B", venue: "San Francisco Bay Area Stadium", matchday: 1 },
  { id: 9, date: "2026-06-14", time: "19:00", home: "Côte d'Ivoire", away: "Ecuador", group: "E", venue: "Philadelphia Stadium", matchday: 1 },
  { id: 10, date: "2026-06-14", time: "13:00", home: "Germany", away: "Curaçao", group: "E", venue: "Houston Stadium", matchday: 1 },
  { id: 11, date: "2026-06-14", time: "16:00", home: "Netherlands", away: "Japan", group: "F", venue: "Dallas Stadium", matchday: 1 },
  { id: 12, date: "2026-06-14", time: "22:00", home: "Sweden", away: "Tunisia", group: "F", venue: "Estadio Monterrey", matchday: 1 },
  { id: 13, date: "2026-06-15", time: "18:00", home: "Saudi Arabia", away: "Uruguay", group: "H", venue: "Miami Stadium", matchday: 1 },
  { id: 14, date: "2026-06-15", time: "12:00", home: "Spain", away: "Cabo Verde", group: "H", venue: "Atlanta Stadium", matchday: 1 },
  { id: 15, date: "2026-06-15", time: "21:00", home: "IR Iran", away: "New Zealand", group: "G", venue: "Los Angeles Stadium", matchday: 1 },
  { id: 16, date: "2026-06-15", time: "15:00", home: "Belgium", away: "Egypt", group: "G", venue: "Seattle Stadium", matchday: 1 },
  { id: 17, date: "2026-06-16", time: "15:00", home: "France", away: "Senegal", group: "I", venue: "New York New Jersey Stadium", matchday: 1 },
  { id: 18, date: "2026-06-16", time: "18:00", home: "Iraq", away: "Norway", group: "I", venue: "Boston Stadium", matchday: 1 },
  { id: 19, date: "2026-06-16", time: "21:00", home: "Argentina", away: "Algeria", group: "J", venue: "Kansas City Stadium", matchday: 1 },
  { id: 20, date: "2026-06-17", time: "00:00", home: "Austria", away: "Jordan", group: "J", venue: "San Francisco Bay Area Stadium", matchday: 1 },
  { id: 21, date: "2026-06-17", time: "19:00", home: "Ghana", away: "Panama", group: "L", venue: "Toronto Stadium", matchday: 1 },
  { id: 22, date: "2026-06-17", time: "16:00", home: "England", away: "Croatia", group: "L", venue: "Dallas Stadium", matchday: 1 },
  { id: 23, date: "2026-06-17", time: "13:00", home: "Portugal", away: "Congo DR", group: "K", venue: "Houston Stadium", matchday: 1 },
  { id: 24, date: "2026-06-17", time: "22:00", home: "Uzbekistan", away: "Colombia", group: "K", venue: "Mexico City Stadium", matchday: 1 },

  { id: 25, date: "2026-06-18", time: "12:00", home: "Czechia", away: "South Africa", group: "A", venue: "Atlanta Stadium", matchday: 2 },
  { id: 26, date: "2026-06-18", time: "15:00", home: "Switzerland", away: "Bosnia and Herzegovina", group: "B", venue: "Los Angeles Stadium", matchday: 2 },
  { id: 27, date: "2026-06-18", time: "18:00", home: "Canada", away: "Qatar", group: "B", venue: "BC Place Vancouver", matchday: 2 },
  { id: 28, date: "2026-06-18", time: "21:00", home: "Mexico", away: "Korea Republic", group: "A", venue: "Estadio Guadalajara", matchday: 2 },
  { id: 29, date: "2026-06-19", time: "20:30", home: "Brazil", away: "Haiti", group: "C", venue: "Philadelphia Stadium", matchday: 2 },
  { id: 30, date: "2026-06-19", time: "18:00", home: "Scotland", away: "Morocco", group: "C", venue: "Boston Stadium", matchday: 2 },
  { id: 31, date: "2026-06-19", time: "23:00", home: "Türkiye", away: "Paraguay", group: "D", venue: "San Francisco Bay Area Stadium", matchday: 2 },
  { id: 32, date: "2026-06-19", time: "15:00", home: "USA", away: "Australia", group: "D", venue: "Seattle Stadium", matchday: 2 },
  { id: 33, date: "2026-06-20", time: "16:00", home: "Germany", away: "Côte d'Ivoire", group: "E", venue: "Toronto Stadium", matchday: 2 },
  { id: 34, date: "2026-06-20", time: "20:00", home: "Ecuador", away: "Curaçao", group: "E", venue: "Kansas City Stadium", matchday: 2 },
  { id: 35, date: "2026-06-20", time: "13:00", home: "Netherlands", away: "Sweden", group: "F", venue: "Houston Stadium", matchday: 2 },
  { id: 36, date: "2026-06-21", time: "00:00", home: "Tunisia", away: "Japan", group: "F", venue: "Estadio Monterrey", matchday: 2 },
  { id: 37, date: "2026-06-21", time: "18:00", home: "Uruguay", away: "Cabo Verde", group: "H", venue: "Miami Stadium", matchday: 2 },
  { id: 38, date: "2026-06-21", time: "12:00", home: "Spain", away: "Saudi Arabia", group: "H", venue: "Atlanta Stadium", matchday: 2 },
  { id: 39, date: "2026-06-21", time: "15:00", home: "Belgium", away: "IR Iran", group: "G", venue: "Los Angeles Stadium", matchday: 2 },
  { id: 40, date: "2026-06-21", time: "21:00", home: "New Zealand", away: "Egypt", group: "G", venue: "BC Place Vancouver", matchday: 2 },
  { id: 41, date: "2026-06-22", time: "20:00", home: "Norway", away: "Senegal", group: "I", venue: "New York New Jersey Stadium", matchday: 2 },
  { id: 42, date: "2026-06-22", time: "17:00", home: "France", away: "Iraq", group: "I", venue: "Philadelphia Stadium", matchday: 2 },
  { id: 43, date: "2026-06-22", time: "13:00", home: "Argentina", away: "Austria", group: "J", venue: "Dallas Stadium", matchday: 2 },
  { id: 44, date: "2026-06-22", time: "23:00", home: "Jordan", away: "Algeria", group: "J", venue: "San Francisco Bay Area Stadium", matchday: 2 },
  { id: 45, date: "2026-06-23", time: "16:00", home: "England", away: "Ghana", group: "L", venue: "Boston Stadium", matchday: 2 },
  { id: 46, date: "2026-06-23", time: "19:00", home: "Panama", away: "Croatia", group: "L", venue: "Toronto Stadium", matchday: 2 },
  { id: 47, date: "2026-06-23", time: "13:00", home: "Portugal", away: "Uzbekistan", group: "K", venue: "Houston Stadium", matchday: 2 },
  { id: 48, date: "2026-06-23", time: "22:00", home: "Colombia", away: "Congo DR", group: "K", venue: "Estadio Guadalajara", matchday: 2 },

  { id: 49, date: "2026-06-24", time: "18:00", home: "Scotland", away: "Brazil", group: "C", venue: "Miami Stadium", matchday: 3 },
  { id: 50, date: "2026-06-24", time: "18:00", home: "Morocco", away: "Haiti", group: "C", venue: "Atlanta Stadium", matchday: 3 },
  { id: 51, date: "2026-06-24", time: "15:00", home: "Switzerland", away: "Canada", group: "B", venue: "BC Place Vancouver", matchday: 3 },
  { id: 52, date: "2026-06-24", time: "15:00", home: "Bosnia and Herzegovina", away: "Qatar", group: "B", venue: "Seattle Stadium", matchday: 3 },
  { id: 53, date: "2026-06-24", time: "21:00", home: "Czechia", away: "Mexico", group: "A", venue: "Mexico City Stadium", matchday: 3 },
  { id: 54, date: "2026-06-24", time: "21:00", home: "South Africa", away: "Korea Republic", group: "A", venue: "Estadio Monterrey", matchday: 3 },
  { id: 55, date: "2026-06-25", time: "16:00", home: "Curaçao", away: "Côte d'Ivoire", group: "E", venue: "Philadelphia Stadium", matchday: 3 },
  { id: 56, date: "2026-06-25", time: "16:00", home: "Ecuador", away: "Germany", group: "E", venue: "New York New Jersey Stadium", matchday: 3 },
  { id: 57, date: "2026-06-25", time: "19:00", home: "Japan", away: "Sweden", group: "F", venue: "Dallas Stadium", matchday: 3 },
  { id: 58, date: "2026-06-25", time: "19:00", home: "Tunisia", away: "Netherlands", group: "F", venue: "Kansas City Stadium", matchday: 3 },
  { id: 59, date: "2026-06-25", time: "22:00", home: "Türkiye", away: "USA", group: "D", venue: "Los Angeles Stadium", matchday: 3 },
  { id: 60, date: "2026-06-25", time: "22:00", home: "Paraguay", away: "Australia", group: "D", venue: "San Francisco Bay Area Stadium", matchday: 3 },
  { id: 61, date: "2026-06-26", time: "15:00", home: "Norway", away: "France", group: "I", venue: "Boston Stadium", matchday: 3 },
  { id: 62, date: "2026-06-26", time: "15:00", home: "Senegal", away: "Iraq", group: "I", venue: "Toronto Stadium", matchday: 3 },
  { id: 63, date: "2026-06-26", time: "23:00", home: "Egypt", away: "IR Iran", group: "G", venue: "Seattle Stadium", matchday: 3 },
  { id: 64, date: "2026-06-26", time: "23:00", home: "New Zealand", away: "Belgium", group: "G", venue: "BC Place Vancouver", matchday: 3 },
  { id: 65, date: "2026-06-26", time: "20:00", home: "Cabo Verde", away: "Saudi Arabia", group: "H", venue: "Houston Stadium", matchday: 3 },
  { id: 66, date: "2026-06-26", time: "20:00", home: "Uruguay", away: "Spain", group: "H", venue: "Estadio Guadalajara", matchday: 3 },
  { id: 67, date: "2026-06-27", time: "17:00", home: "Panama", away: "England", group: "L", venue: "New York New Jersey Stadium", matchday: 3 },
  { id: 68, date: "2026-06-27", time: "17:00", home: "Croatia", away: "Ghana", group: "L", venue: "Philadelphia Stadium", matchday: 3 },
  { id: 69, date: "2026-06-27", time: "22:00", home: "Algeria", away: "Austria", group: "J", venue: "Kansas City Stadium", matchday: 3 },
  { id: 70, date: "2026-06-27", time: "22:00", home: "Jordan", away: "Argentina", group: "J", venue: "Dallas Stadium", matchday: 3 },
  { id: 71, date: "2026-06-27", time: "19:30", home: "Colombia", away: "Portugal", group: "K", venue: "Miami Stadium", matchday: 3 },
  { id: 72, date: "2026-06-27", time: "19:30", home: "Congo DR", away: "Uzbekistan", group: "K", venue: "Atlanta Stadium", matchday: 3 }
];
